apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  template:
    spec:
      containers:
        - name: db
          env:
            - name: NEO4J_dbms_memory_heap_max_size
            value: "3072M"
            - name: NEO4J_dbms_transaction_timeout
            value: "180s"
            - name: NEO4J_dbms_memory_pagecache_size
            value: "3072M"
